version: 1.0.{build}
image: Visual Studio 2017 Preview
before_build:
- cmd: dotnet restore
- choco install opencover
build:
  project: Mp3MusicZone.sln
  verbosity: minimal
build_script:
 - msbuild /verbosity:quiet "Mp3MusicZone.sln"
test_script:
 - OpenCover.Console.exe -target:"c:\Program Files\dotnet\dotnet.exe" -targetargs:"test C:\projects\mp3music\Mp3MusicZone.UnitTests\Mp3MusicZone.UnitTests.csproj" -output:"coverage.xml" -oldStyle -filter:"+[Mp3MusicZone*]* -[*Tests*]*" -register:user
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 2a032ebf-eb46-4114-93da-ba8b0088b02d
      
     