version: 1.0.{build}
image: Visual Studio 2017 Preview
before_build:
- cmd: dotnet restore
- choco install opencover
build:
  project: Mp3MusicZone.sln
  verbosity: minimal
build_script:
 - msbuild /verbosity:quiet "Mp3MusicZone.sln"
test_script:
 - OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"Mp3MusicZone.UnitTests.dll -noshadow" -output:"coverage.xml" -filter:"+[Mp3MusicZone*]* -[*Tests]*" -oldStyle 
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 2a032ebf-eb46-4114-93da-ba8b0088b02d
      
     