version: 1.1.{build}
image: Visual Studio 2017 Preview
branches:
  only:
  - never-build-branch-automatically-dont-use-this-name
environment:
  usernamePassword:
    secure: 9355KTIDMhE43lIhZPfiQA==
before_build:
 - cmd: dotnet --version
 - cmd: dotnet restore --verbosity m
configuration: 
  - Release 
build:
 project: Mp3MusicZone.sln
 verbosity: minimal
build_script:
 - msbuild /verbosity:quiet "Mp3MusicZone.sln"
 - cmd: dotnet publish ./Mp3MusicZone.Web/Mp3MusicZone.Web.csproj
artifacts:
 - path: '.\Mp3MusicZone.Web\bin\Release\netcoreapp2.1\publish'
   name: WebSite
   type: WebDeployPackage
before_test:
  - ps: |
      echo '{
        "ConnectionStrings": {
           "MusicZoneConnectionString": "Server=(local)\\SQL2017;Database=Mp3ZoneDB-SIT;Trusted_Connection=True;MultipleActiveResultSets=true;User Id=sa;Password=Password12!"
        }
      }' > '.\Mp3MusicZone.IntegrationTests\appsettings.json'
test_script:
 - cmd: dotnet test .\Mp3MusicZone.UnitTests\Mp3MusicZone.UnitTests.csproj -c Release --logger:"trx;LogFileName=UnitTestsResults.trx"
 - cmd: dotnet test .\Mp3MusicZone.IntegrationTests\Mp3MusicZone.IntegrationTests.csproj -c Release --logger:"trx;LogFileName=IntegrationTestsResults.trx"
after_test:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $resultsUnitTests = Resolve-Path .\Mp3MusicZone.UnitTests\TestResults\*.trx
      $resultsIntegrationTests = Resolve-Path .\Mp3MusicZone.IntegrationTests\TestResults\*.trx
      Write-Host "$($resultsUnitTests[0]) $($resultsIntegrationTests[0])"
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", ($resultsUnitTests[0]))
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", ($resultsIntegrationTests[0]))
deploy:
 provider: WebDeploy
 server: https://mp3musiczone.scm.azurewebsites.net:443/msdeploy.axd?site=mp3musiczone
 website: mp3musiczone
 username: $mp3musiczone
 password: 0whg4tpi5hLETJGkeyHwv6jaf6CZGNXytWRTM4zJRodfJ4xHhfksh0wFQ6nl
 name: "Mp3MusicZone-Live"
 artifact: WebSite
services:
  - mssql2017