version: 1.1.{build}
image: Visual Studio 2017 Preview
branches:
  only:
  - master
before_build:
 - cmd: dotnet --version
 - cmd: dotnet restore --verbosity m
 - choco install opencover
configuration: 
  - Release 
build:
 project: Mp3MusicZone.sln
 verbosity: minimal
build_script:
 - msbuild /verbosity:quiet "Mp3MusicZone.sln"
 - cmd: dotnet publish ./Mp3MusicZone.Web/Mp3MusicZone.Web.csproj
artifacts:
 - path: '.\Mp3MusicZone.Web\bin\Release\netcoreapp2.1\publish'
   name: WebSite
   type: WebDeployPackage
test_script:
 - OpenCover.Console.exe -target:"c:\Program Files\dotnet\dotnet.exe" -targetargs:"test C:\projects\mp3music\Mp3MusicZone.UnitTests\Mp3MusicZone.UnitTests.csproj" -output:"coverage.xml" -oldStyle -filter:"+[Mp3MusicZone*]* -[*Tests*]*" -register:user
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 2a032ebf-eb46-4114-93da-ba8b0088b02d
deploy:
  provider: Environment
  name: Mp3MusicZone-Live      
      
	  
	  
      
     