version: 1.1.{build}
image: Visual Studio 2017 Preview
branches:
  only:
  - never-build-branch-automatically-dont-use-this-name
before_build:
 - cmd: dotnet --version
 - cmd: dotnet restore --verbosity m
 - choco install opencover
configuration: 
  - Release 
build:
 project: Mp3MusicZone.sln
 verbosity: minimal
build_script:
 - msbuild /verbosity:quiet "Mp3MusicZone.sln"
 - cmd: dotnet publish ./Mp3MusicZone.Web/Mp3MusicZone.Web.csproj
artifacts:
 - path: '.\Mp3MusicZone.Web\bin\Release\netcoreapp2.1\publish'
   name: WebSite
   type: WebDeployPackage
test:
- cmd: dotnet test .\Mp3MusicZone.UnitTests\Mp3MusicZone.UnitTests.csproj -c Release --logger:"trx;LogFileName=UnitTestsResults.trx"
test_script:
ps: |
    $wc = New-Object 'System.Net.WebClient'
    $results = Resolve-Path .\Mp3MusicZone.UnitTests\TestResults\*.trx
    $results = $results[0]
    Write-Host $results
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", ($results))
deploy:
 provider: Environment
 name: "Mp3MusicZone-Live"