version: 1.1.{build}
image: Visual Studio 2017 Preview
branches:
  only:
  - never-build-branch-automatically-dont-use-this-name
before_build:
 - cmd: dotnet --version
 - cmd: dotnet restore --verbosity m
 - choco install opencover
configuration: 
  - Release 
build:
 project: Mp3MusicZone.sln
 verbosity: minimal
build_script:
 - msbuild /verbosity:quiet "Mp3MusicZone.sln"
 - cmd: dotnet publish ./Mp3MusicZone.Web/Mp3MusicZone.Web.csproj
artifacts:
 - path: '.\Mp3MusicZone.Web\bin\Release\netcoreapp2.1\publish'
   name: WebSite
   type: WebDeployPackage
test_script:
 - nunit3-console '.\Mp3MusicZone.UnitTests\bin\Release\netcoreapp2.1\Mp3MusicZone.UnitTests.dll' --result=myresults.xml;format=AppVeyor
deploy:
 provider: Environment
 name: "Mp3MusicZone-Live"